name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener token desde GitHub App
      id: auth
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Configurar Git para GitHub App
      run: |
        git config --global url."https://x-access-token:${{ steps.auth.outputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Configurar SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 200.16.7.169 >> ~/.ssh/known_hosts

    - name: Ejecutar script remoto
      run: ssh amercado@200.16.7.169 "bash /home/amercado/deploy_frontend.sh"
